---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: fluxdemo-prod
  name: fluxdemo-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: fluxdemo-prod
  name: fluxdemo-prod
  namespace: fluxdemo-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: fluxdemo-prod
  name: fluxdemo-prod-reconciler
  namespace: fluxdemo-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:fluxdemo-prod:reconciler
- kind: ServiceAccount
  name: fluxdemo-prod
  namespace: fluxdemo-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: prod
  namespace: fluxdemo-prod
  annotations:
    kubernetes.io/service-account.name: fluxdemo-prod
type: kubernetes.io/service-account-token
