---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: fluxdemo-stage
  name: fluxdemo-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: fluxdemo-stage
  name: fluxdemo-stage
  namespace: fluxdemo-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: fluxdemo-stage
  name: fluxdemo-stage-reconciler
  namespace: fluxdemo-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:fluxdemo-stage:reconciler
- kind: ServiceAccount
  name: fluxdemo-stage
  namespace: fluxdemo-stage
---
apiVersion: v1
kind: Secret
metadata:
  name: stage
  namespace: fluxdemo-stage
  annotations:
    kubernetes.io/service-account.name: fluxdemo-stage
type: kubernetes.io/service-account-token
